spring:
  application:
    name: billing-service
  kafka:
    bootstrap-servers: localhost:9292
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: batch-workers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/billing}
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  batch:
    jdbc:
      initialize-schema: always
server:
  port: ${SERVER_PORT}
grpc:
  server:
    port: ${GRPC_PORT}
