spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patient
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: patient-service
  sql:
    init:
      mode: always
server:
  port: 4000